config/routes.rb
Rails.application.routes.draw do
  resources :classifications

  resources :participants do
		member do
			put :check
		end

		collection do
			post :search
			get :checked
			get :unchecked
		end
	end

	root "participants#index"

end

app/models/classification.rb
class Classification < ActiveRecord::Base
	has_many :participant
end

app/models/participant.rb
class Participant < ActiveRecord::Base
	belongs_to :classification
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	# Change user and password accoding to your environment
	USERS = { 'user' => 'password' }

	before_action :digest_auth

	def digest_auth
		authenticate_or_request_with_http_digest do |user|
			USERS[user]
		end
	end
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  before_action :set_classification, only: [:show, :edit, :update, :destroy]

  # GET /classifications
  # GET /classifications.json
  def index
    @classifications = Classification.all
  end

  # GET /classifications/1
  # GET /classifications/1.json
  def show
  end

  # GET /classifications/new
  def new
    @classification = Classification.new
  end

  # GET /classifications/1/edit
  def edit
  end

  # POST /classifications
  # POST /classifications.json
  def create
    @classification = Classification.new(classification_params)

    respond_to do |format|
      if @classification.save
        format.html { redirect_to @classification, notice: 'Classification was successfully created.' }
        format.json { render :show, status: :created, location: @classification }
      else
        format.html { render :new }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classifications/1
  # PATCH/PUT /classifications/1.json
  def update
    respond_to do |format|
      if @classification.update(classification_params)
        format.html { redirect_to @classification, notice: 'Classification was successfully updated.' }
        format.json { render :show, status: :ok, location: @classification }
      else
        format.html { render :edit }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifications/1
  # DELETE /classifications/1.json
  def destroy
    @classification.destroy
    respond_to do |format|
      format.html { redirect_to classifications_url, notice: 'Classification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classification
      @classification = Classification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classification_params
      params.require(:classification).permit(:name)
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
	before_action :set_participant, only: [:show, :edit, :update, :destroy, :check]
	before_action :set_participants, only: [:index ,:search, :checked, :unchecked]

	# GET /participants
	# GET /participants.json
	def index
		@classifications.each do |classification|
			@participants.push(Participant.where("classification_id = ?", classification.id))
		end
	end

	# GET /participants/1
	# GET /participants/1.json
	def show
	end

	# GET /participants/new
	def new
		@participant = Participant.new
	end

	# GET /participants/1/edit
	def edit
	end

	# POST /participants
	# POST /participants.json
	def create
		@participant = Participant.new(participant_params)

		respond_to do |format|
			if @participant.save
				format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
				format.json { render :show, status: :created, location: @participant }
			else
				format.html { render :new }
				format.json { render json: @participant.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /participants/1
	# PATCH/PUT /participants/1.json
	def update
		respond_to do |format|
			if @participant.update(participant_params)
				format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
				format.json { render :show, status: :ok, location: @participant }
			else
				format.html { render :edit }
				format.json { render json: @participant.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /participants/1
	# DELETE /participants/1.json
	def destroy
		@participant.destroy
		respond_to do |format|
			format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def check
		@participant.status = true
		if @participant.update(status: true)
			redirect_to participants_path
		else
			redirect_to participants_path, alert: "Failed to change status"
		end
	end

	def search
		@classifications.each do |classification|
			@participants.push(Participant.where("classification_id = ? AND name like ?", classification.id, "%#{params[:s_name]}%"))
		end
    render :index
	end

	def checked
		@classifications.each do |classification|
			@participants.push(Participant.where("classification_id = ? AND status = ?", classification.id, true))
		end
		render :index
	end

	def unchecked
		@classifications.each do |classification|
			@participants.push(Participant.where("classification_id = ? AND status = ?", classification.id, false))
		end
		render :index
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_participant
		@participant = Participant.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def participant_params
		params.require(:participant).permit(:name, :classification_id, :status, :s_name)
	end

	def set_participants
		@participants = Array.new
		@classifications = Classification.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/classifications/_form.html.erb
<%= form_for(@classification) do |f| %>
  <% if @classification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classification.errors.count, "error") %> prohibited this classification from being saved:</h2>

      <ul>
      <% @classification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classifications/edit.html.erb
<h1>Editing classification</h1>

<%= render 'form' %>

<%= link_to 'Show', @classification %> |
<%= link_to 'Back', classifications_path %>

app/views/classifications/index.html.erb
<h1>Listing classifications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classifications.each do |classification| %>
      <tr>
        <td><%= classification.name %></td>
        <td><%= link_to 'Show', classification %></td>
        <td><%= link_to 'Edit', edit_classification_path(classification) %></td>
        <td><%= link_to 'Destroy', classification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classification', new_classification_path %>

app/views/classifications/new.html.erb
<h1>New classification</h1>

<%= render 'form' %>

<%= link_to 'Back', classifications_path %>

app/views/classifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @classification.name %>
</p>

<%= link_to 'Edit', edit_classification_path(@classification) %> |
<%= link_to 'Back', classifications_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AttendanceChecker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">AttendanceChecker</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "All", participants_path %></li>
            <li><%= link_to "Checked", checked_participants_path %></li>
            <li><%= link_to "Unchecked", unchecked_participants_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Hiromu Kamei 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :classification_id %><br>
    <%= f.number_field :classification_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/_participants_table.erb
<% i = 0 %>
<% @classifications.each do |classification| %>
  <h2><span class="glyphicon glyphicon-asterisk text-danger" aria-hidden="true"></span> <%= classification.name %></h2>
  <div class="table-responsive">
    <table class="table table-hover">
			<thead>
				<tr>
					<th class="col-xs-3">Name</th>
					<th class="col-xs-3">Details</th>
					<th class="col-xs-3">Status</th>
					<th class="col-xs-3">Check</th>
				</tr>
			</thead>

			<tbody>
				<% @participants[i].each do |participant| %>
					<tr>
						<td><%= participant.name %></td>
						<td><%= link_to 'Show', participant %></td>
						<% if participant.status %>
							<td><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span></td>
							<td><button type="button" class="btn btn-default">Checked</button></td>
						<% else %>
							<td><span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span></td>
							<td><%= button_to 'Check', check_participant_path(participant), method: :put, class: "btn btn-primary" %></td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<% i = i+1 %>
<% end %>

app/views/participants/_participants_table.html.erb
<% i = 0 %>
<% @classifications.each do |classification| %>
	<h2><span class="glyphicon glyphicon-asterisk text-danger" aria-hidden="true"></span> <%= classification.name %></h2>
	<div class="table-responsive">
		<table class="table table-hover">
			<thead>
				<tr>
					<th class="col-xs-3">Name</th>
					<th class="col-xs-3">Details</th>
					<th class="col-xs-3">Status</th>
					<th class="col-xs-3">Check</th>
				</tr>
			</thead>

			<tbody>
				<% @participants[i].each do |participant| %>
					<tr>
						<td><%= participant.name %></td>
						<td><%= link_to 'Show', participant %></td>
						<% if participant.status %>
							<td><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span></td>
							<td><button type="button" class="btn btn-default">Checked</button></td>
						<% else %>
							<td><span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span></td>
							<td><%= button_to 'Check', check_participant_path(participant), method: :put, class: "btn btn-primary" %></td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<% i = i+1 %>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Participants' List</h1>
<p>下のテキストボックスに名前を入力すると検索できます.</p>
<%= form_tag('/participants/search', method: :post, class: 'form-inline') do %>
  <div class="form-group">
    <%= text_field_tag :s_name, nil, placeholder: 'Input name here!', class: 'form-control' %>
  </div>
  <%= submit_tag 'Search', class: 'btn btn-success' %>
<% end %>
<br>
<%= render 'participants_table', layout: "application" %>
<br>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/search.js.erb
$('#ajax-wrapper').html('<%=j(render partial: "participants_table", collections: @participants) %>');

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<p>
  <strong>Classification_id:</strong>
  <%= @participant.classification_id %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @participant.classification.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @participant.status %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %> |
<%= link_to 'Destroy', @participant, method: :delete, data: { confirm: 'Are you sure?' } %>